/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./src/**/*.{js,ts,jsx,tsx}",
    "../../apps/app-react/src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Semantic color tokens
        background: {
          DEFAULT: "rgb(var(--color-background-primary))",
          secondary: "rgb(var(--color-background-secondary))",
          tertiary: "rgb(var(--color-background-tertiary))",
          elevated: "rgb(var(--color-background-elevated))",
        },
        foreground: {
          DEFAULT: "rgb(var(--color-text-primary))",
          secondary: "rgb(var(--color-text-secondary))",
          tertiary: "rgb(var(--color-text-tertiary))",
          disabled: "rgb(var(--color-text-disabled))",
          inverse: "rgb(var(--color-text-inverse))",
        },
        border: {
          DEFAULT: "rgb(var(--color-border-primary))",
          secondary: "rgb(var(--color-border-secondary))",
          focus: "rgb(var(--color-border-focus))",
          error: "rgb(var(--color-border-error))",
          success: "rgb(var(--color-border-success))",
          warning: "rgb(var(--color-border-warning))",
        },
        primary: {
          DEFAULT: "rgb(var(--color-interactive-primary))",
          hover: "rgb(var(--color-interactive-primary-hover))",
          active: "rgb(var(--color-interactive-primary-active))",
          disabled: "rgb(var(--color-interactive-primary-disabled))",
          foreground: "rgb(var(--color-text-inverse))",
        },
        secondary: {
          DEFAULT: "rgb(var(--color-interactive-secondary))",
          hover: "rgb(var(--color-interactive-secondary-hover))",
          active: "rgb(var(--color-interactive-secondary-active))",
          foreground: "rgb(var(--color-text-primary))",
        },
        destructive: {
          DEFAULT: "rgb(var(--color-interactive-destructive))",
          hover: "rgb(var(--color-interactive-destructive-hover))",
          active: "rgb(var(--color-interactive-destructive-active))",
          foreground: "rgb(var(--color-text-inverse))",
        },
        success: {
          DEFAULT: "rgb(var(--color-success-500))",
          foreground: "rgb(var(--color-text-inverse))",
        },
        warning: {
          DEFAULT: "rgb(var(--color-warning-500))",
          foreground: "rgb(var(--color-text-inverse))",
        },
        muted: {
          DEFAULT: "rgb(var(--color-background-secondary))",
          foreground: "rgb(var(--color-text-tertiary))",
        },
        accent: {
          DEFAULT: "rgb(var(--color-background-secondary))",
          foreground: "rgb(var(--color-text-primary))",
        },
        card: {
          DEFAULT: "rgb(var(--color-background-elevated))",
          foreground: "rgb(var(--color-text-primary))",
        },
        popover: {
          DEFAULT: "rgb(var(--color-background-elevated))",
          foreground: "rgb(var(--color-text-primary))",
        },
        input: "rgb(var(--color-border-primary))",
        ring: "rgb(var(--color-border-focus))",
        
        // Raw color tokens for advanced usage
        'color-primary': {
          50: "rgb(var(--color-primary-50))",
          100: "rgb(var(--color-primary-100))",
          200: "rgb(var(--color-primary-200))",
          300: "rgb(var(--color-primary-300))",
          400: "rgb(var(--color-primary-400))",
          500: "rgb(var(--color-primary-500))",
          600: "rgb(var(--color-primary-600))",
          700: "rgb(var(--color-primary-700))",
          800: "rgb(var(--color-primary-800))",
          900: "rgb(var(--color-primary-900))",
          950: "rgb(var(--color-primary-950))",
        },
        'color-neutral': {
          50: "rgb(var(--color-neutral-50))",
          100: "rgb(var(--color-neutral-100))",
          200: "rgb(var(--color-neutral-200))",
          300: "rgb(var(--color-neutral-300))",
          400: "rgb(var(--color-neutral-400))",
          500: "rgb(var(--color-neutral-500))",
          600: "rgb(var(--color-neutral-600))",
          700: "rgb(var(--color-neutral-700))",
          800: "rgb(var(--color-neutral-800))",
          900: "rgb(var(--color-neutral-900))",
          950: "rgb(var(--color-neutral-950))",
        },
        'color-success': {
          50: "rgb(var(--color-success-50))",
          100: "rgb(var(--color-success-100))",
          200: "rgb(var(--color-success-200))",
          300: "rgb(var(--color-success-300))",
          400: "rgb(var(--color-success-400))",
          500: "rgb(var(--color-success-500))",
          600: "rgb(var(--color-success-600))",
          700: "rgb(var(--color-success-700))",
          800: "rgb(var(--color-success-800))",
          900: "rgb(var(--color-success-900))",
          950: "rgb(var(--color-success-950))",
        },
        'color-warning': {
          50: "rgb(var(--color-warning-50))",
          100: "rgb(var(--color-warning-100))",
          200: "rgb(var(--color-warning-200))",
          300: "rgb(var(--color-warning-300))",
          400: "rgb(var(--color-warning-400))",
          500: "rgb(var(--color-warning-500))",
          600: "rgb(var(--color-warning-600))",
          700: "rgb(var(--color-warning-700))",
          800: "rgb(var(--color-warning-800))",
          900: "rgb(var(--color-warning-900))",
          950: "rgb(var(--color-warning-950))",
        },
        'color-error': {
          50: "rgb(var(--color-error-50))",
          100: "rgb(var(--color-error-100))",
          200: "rgb(var(--color-error-200))",
          300: "rgb(var(--color-error-300))",
          400: "rgb(var(--color-error-400))",
          500: "rgb(var(--color-error-500))",
          600: "rgb(var(--color-error-600))",
          700: "rgb(var(--color-error-700))",
          800: "rgb(var(--color-error-800))",
          900: "rgb(var(--color-error-900))",
          950: "rgb(var(--color-error-950))",
        },
      },
      spacing: {
        // Use design token spacing
        '0': 'var(--spacing-0)',
        'px': 'var(--spacing-px)',
        '0.5': 'var(--spacing-0_5)',
        '1': 'var(--spacing-1)',
        '1.5': 'var(--spacing-1_5)',
        '2': 'var(--spacing-2)',
        '2.5': 'var(--spacing-2_5)',
        '3': 'var(--spacing-3)',
        '3.5': 'var(--spacing-3_5)',
        '4': 'var(--spacing-4)',
        '5': 'var(--spacing-5)',
        '6': 'var(--spacing-6)',
        '7': 'var(--spacing-7)',
        '8': 'var(--spacing-8)',
        '9': 'var(--spacing-9)',
        '10': 'var(--spacing-10)',
        '11': 'var(--spacing-11)',
        '12': 'var(--spacing-12)',
        '14': 'var(--spacing-14)',
        '16': 'var(--spacing-16)',
        '20': 'var(--spacing-20)',
        '24': 'var(--spacing-24)',
        '28': 'var(--spacing-28)',
        '32': 'var(--spacing-32)',
        '36': 'var(--spacing-36)',
        '40': 'var(--spacing-40)',
        '44': 'var(--spacing-44)',
        '48': 'var(--spacing-48)',
        '52': 'var(--spacing-52)',
        '56': 'var(--spacing-56)',
        '60': 'var(--spacing-60)',
        '64': 'var(--spacing-64)',
        '72': 'var(--spacing-72)',
        '80': 'var(--spacing-80)',
        '96': 'var(--spacing-96)',
      },
      fontSize: {
        'xs': ['var(--font-size-xs)', { lineHeight: 'var(--line-height-tight)' }],
        'sm': ['var(--font-size-sm)', { lineHeight: 'var(--line-height-normal)' }],
        'base': ['var(--font-size-base)', { lineHeight: 'var(--line-height-normal)' }],
        'lg': ['var(--font-size-lg)', { lineHeight: 'var(--line-height-normal)' }],
        'xl': ['var(--font-size-xl)', { lineHeight: 'var(--line-height-normal)' }],
        '2xl': ['var(--font-size-2xl)', { lineHeight: 'var(--line-height-tight)' }],
        '3xl': ['var(--font-size-3xl)', { lineHeight: 'var(--line-height-tight)' }],
        '4xl': ['var(--font-size-4xl)', { lineHeight: 'var(--line-height-tight)' }],
        '5xl': ['var(--font-size-5xl)', { lineHeight: 'var(--line-height-none)' }],
        '6xl': ['var(--font-size-6xl)', { lineHeight: 'var(--line-height-none)' }],
        '7xl': ['var(--font-size-7xl)', { lineHeight: 'var(--line-height-none)' }],
        '8xl': ['var(--font-size-8xl)', { lineHeight: 'var(--line-height-none)' }],
        '9xl': ['var(--font-size-9xl)', { lineHeight: 'var(--line-height-none)' }],
      },
      fontWeight: {
        'thin': 'var(--font-weight-thin)',
        'extralight': 'var(--font-weight-extralight)',
        'light': 'var(--font-weight-light)',
        'normal': 'var(--font-weight-normal)',
        'medium': 'var(--font-weight-medium)',
        'semibold': 'var(--font-weight-semibold)',
        'bold': 'var(--font-weight-bold)',
        'extrabold': 'var(--font-weight-extrabold)',
        'black': 'var(--font-weight-black)',
      },
      borderRadius: {
        'none': 'var(--radius-none)',
        'sm': 'var(--radius-sm)',
        'DEFAULT': 'var(--radius-base)',
        'md': 'var(--radius-md)',
        'lg': 'var(--radius-lg)',
        'xl': 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        '3xl': 'var(--radius-3xl)',
        'full': 'var(--radius-full)',
      },
      boxShadow: {
        'xs': 'var(--shadow-xs)',
        'sm': 'var(--shadow-sm)',
        'DEFAULT': 'var(--shadow-base)',
        'md': 'var(--shadow-md)',
        'lg': 'var(--shadow-lg)',
        'xl': 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
        'inner': 'var(--shadow-inner)',
        'none': 'var(--shadow-none)',
      },
      zIndex: {
        'hide': 'var(--z-index-hide)',
        'auto': 'var(--z-index-auto)',
        '0': 'var(--z-index-base)',
        '10': 'var(--z-index-docked)',
        '50': 'var(--z-index-dropdown)',
        '100': 'var(--z-index-sticky)',
        '200': 'var(--z-index-banner)',
        '300': 'var(--z-index-overlay)',
        '400': 'var(--z-index-modal)',
        '500': 'var(--z-index-popover)',
        '600': 'var(--z-index-skipLink)',
        '700': 'var(--z-index-toast)',
        '800': 'var(--z-index-tooltip)',
      },
      transitionProperty: {
        'none': 'var(--transition-none)',
        'all': 'var(--transition-all)',
        'colors': 'var(--transition-colors)',
        'opacity': 'var(--transition-opacity)',
        'shadow': 'var(--transition-shadow)',
        'transform': 'var(--transition-transform)',
      },
      screens: {
        'sm': 'var(--breakpoint-sm)',
        'md': 'var(--breakpoint-md)',
        'lg': 'var(--breakpoint-lg)',
        'xl': 'var(--breakpoint-xl)',
        '2xl': 'var(--breakpoint-2xl)',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [],
}
